version: "3"

services:

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

    ports:
      - "80:80"

  oc_battleships:
    build: ./
    image: oc_battleships

    ports:
      - "3000:3000"

    environment:
      - BATTLESHIP_TOKEN=444
