# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/clojure:lein-2.7.1
      
    working_directory: ~/repo

    environment:
      LEIN_ROOT: "true"
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
    
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "project.clj" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: lein deps

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "project.clj" }}
        
      # run tests!
      - run:
          name: Test
          command: lein test

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Build and push docker image
          command: |
            docker build -t shaolinsarg/$IMAGE_NAME:latest .
            echo $DOCKER_PWD | docker login -u $DOCKER_USER --password-stdin
            docker push shaolinsarg/$IMAGE_NAME:latest

  deploy:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "7e:a2:52:91:bf:4b:8e:99:eb:10:f9:63:23:66:de:df"
      - run:
          name: Deploy Over SSH
          command: |
            ssh $SSH_USER@$SSH_HOST "echo 'deploying' > deployed.txt"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          context: dockerhub 
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
